"""`docs/COMMAND-REFERENCE.md` cannot silently drift from the live parser.

The file is generated by `scripts/dev/build_command_reference.py`, never
hand-edited. This guards that promise three ways: the committed file is
byte-for-byte what the generator would write today; the row set is exactly
the live parser's verb set, read straight from it here via
`build_command_reference.verbs_and_help()` (a new verb with no
regeneration fails here, not in a downstream `selftest` run, which reads
the committed doc rather than the parser - see
`godmode_selftest._verbs_from_command_reference` - specifically so that
module never has to import `godmode_console` and close the
console -> assess -> selftest -> console cycle); and every row's Purpose
is exactly the parser's own declared help text for that verb.
"""
from __future__ import annotations

from pathlib import Path
import re
import sys
import unittest

PLUGIN_ROOT = Path(__file__).resolve().parents[1]
SCRIPTS = PLUGIN_ROOT / "scripts"
DEV_SCRIPTS = PLUGIN_ROOT / "scripts" / "dev"
if str(SCRIPTS) not in sys.path:
    sys.path.insert(0, str(SCRIPTS))
if str(DEV_SCRIPTS) not in sys.path:
    sys.path.insert(0, str(DEV_SCRIPTS))

import build_command_reference  # noqa: E402

DOC_PATH = PLUGIN_ROOT / "docs" / "COMMAND-REFERENCE.md"

_ROW = re.compile(r"^\| `([\w-]+)` \| (.*) \| (.*) \|$")


def _committed_rows() -> dict[str, str]:
    """{verb: purpose}, parsed straight from the committed file's own table -
    independent of `render()`, so a bug in the generator that still happens
    to reproduce its own prior output cannot hide from this test."""
    purposes: dict[str, str] = {}
    for line in DOC_PATH.read_text(encoding="utf-8").splitlines():
        match = _ROW.match(line)
        if match:
            verb, purpose, _verify = match.groups()
            purposes[verb] = purpose.replace("\\|", "|")
    return purposes


class CommandReferenceDriftTests(unittest.TestCase):
    def test_committed_file_matches_the_generator(self) -> None:
        generated = build_command_reference.render()
        committed = DOC_PATH.read_text(encoding="utf-8")
        self.assertEqual(
            generated, committed,
            "docs/COMMAND-REFERENCE.md is stale - regenerate with "
            "`python scripts/dev/build_command_reference.py`",
        )

    def test_row_set_equals_the_live_parsers_verbs(self) -> None:
        committed = _committed_rows()
        self.assertTrue(committed, "no table rows parsed from docs/COMMAND-REFERENCE.md")
        live_verbs = {verb for verb, _purpose in build_command_reference.verbs_and_help()}
        self.assertEqual(set(committed), live_verbs)

    def test_every_rows_purpose_is_the_parsers_own_help_text(self) -> None:
        committed = _committed_rows()
        live_help = dict(build_command_reference.verbs_and_help())
        for verb, purpose in committed.items():
            with self.subTest(verb=verb):
                self.assertEqual(purpose, live_help[verb])


if __name__ == "__main__":
    unittest.main()
