"""Sprint L1 of the Code of Law loop: the writer and the slot.

The operator's ask (request 4110, decision 4114): do for every project what
a hand-maintained rules file does for one - a per-project law file, fired at
session start on every host, maintained by godmode itself. L1 is the writer
and the slot: `law compile` folds every lesson that carries a generalized
guard into a bounded `GODMODE-CODE-OF-LAW.md` with provenance, a wrapper
skill carries it to hook-less hosts, the file is a bound authority role so
the charter, `attest` and the required-sources counter consume it with no
new machinery, and the SessionStart brief carries the top laws.

Doctrine constraints, live in this module:
- The file is GENERATED and says so; a hand edit is overwritten. The hand
  file this generalizes rotted exactly because nothing regenerated it.
- Bounded, and the bound is stated in the artifact (no silent caps): laws
  beyond the cap are counted in the file itself.
- Deterministic: same archive, same bytes - no timestamps, no randomness -
  so `bindings`-style drift checks and git diffs stay meaningful.
- Counts and reviewed prose only. A lesson's value and guard were written
  at recording time under the archive's own secret scan; nothing here reads
  prompts or source bodies.

Detectors, receipts and the promotion ladder are L2/L3 (see the spec);
until then every compiled law is ADVISORY and its provenance is the lesson
it came from.
"""
from __future__ import annotations

import re
from pathlib import Path
from typing import Any

LAW_FILENAME = "GODMODE-CODE-OF-LAW.md"
SKILL_DIRNAME = "godmode-code-of-law"
LAW_CAP = 24
WHY_CHARS = 160

_HEADER = f"""# GODMODE CODE OF LAW

Generated by `godmode law compile` from this project's archive. Do not
hand-edit: the next compile overwrites this file. Each law is a lesson this
project recorded with a generalized guard; the sequence number is its
provenance in the hash-chained archive (`godmode slice`/`history` to read
it back). Laws are ADVISORY until the promotion ladder ships; follow the
guard, and when a guard is wrong, retire the lesson rather than ignoring
the law.
"""


def _flatten(text: str) -> str:
    """Collapse internal whitespace/newlines to single spaces, unbounded.

    Guard text is never cut short (D-6): a guard is the whole rule a
    session is meant to follow, and a truncated guard silently reads as a
    smaller rule - which is a wrong one, not a shorter one. This only
    normalizes layout so a multi-line guard still renders as one line.
    """
    return " ".join(str(text).split())


def _ellipsize(text: str, limit: int) -> str:
    """Bound summarized text (Why/provenance only - never Guard) at a word
    boundary. A hard slice at `limit` can land inside a word; this backs up
    to the last space inside the limit so the cut is never mid-word, and
    marks it with "…". Text that already fits is returned complete."""
    flattened = _flatten(text)
    if len(flattened) <= limit:
        return flattened
    truncated = flattened[:limit]
    boundary = truncated.rfind(" ")
    if boundary > 0:
        truncated = truncated[:boundary]
    return truncated.rstrip() + "…"


# I-1 fix round 1 (nit 7): the one shared "not really active" status set -
# `_guarded_lessons` (the law compiler, below) and
# `Chronicle._enforced_refusal` (godmode_chronicle.py, the guard that
# actually refuses writes) used to keep separate, silently-diverging
# copies of this set: a `--status superseded` lesson stopped refusing
# writes but kept rendering as `[ADVISORY]` law in the brief, so an
# operator reading the brief saw a guard the archive no longer enforced.
# One set, imported by `godmode_chronicle.py` rather than copied, so a
# status that retires a lesson for one reader retires it for both.
LESSON_DORMANT_STATUSES = frozenset({"retired", "candidate", "superseded"})


# NS-2 fix round 2 (the upgrade blocker): where the one-time grandfather
# cutoff lives. The gate below is right for every new write and wrong for
# every write that predates it - an archive recorded before the gate
# existed holds guarded lessons with neither approval lineage nor operator
# trust, because neither was asked for at the time, so the first compile
# after an upgrade silently emptied a project's whole Code of Law. The
# remedy is a MIGRATION RECORD, appended once, through the archive's own
# chained append so it is auditable like everything else: it names the
# archive head at migration time, and every guarded lesson at or below that
# sequence keeps its standing. A lesson recorded after it does not - the
# cutoff is a line under the past, never a standing exemption.
#
# `decision` rather than a new kind: the vocabulary already carries "this
# project decided X, here is the evidence", `EVENT_KINDS` is a frozen
# allow-list every reader shares, and a migration IS a decision with a
# scope. The label subject is fixed so the reader below can find it without
# scanning data.
LAW_MIGRATION_KIND = "decision"
LAW_MIGRATION_SUBJECT = "law-authority-grandfather"

# The day the authority gate landed. A lesson recorded BEFORE this date was
# written under rules that never asked for a second actor, and is what the
# migration grandfathers; a lesson recorded on or after it was written with
# the gate in force and is held to it, whenever the project gets around to
# upgrading.
#
# This date is what keeps the migration from becoming the hole the gate
# closed. Without it, "pre-gate" would have to mean "already in the archive
# when the first compile ran", and on a BRAND-NEW project that is satisfied
# by an agent appending its own guard and then compiling - self-legislation
# with one extra step, and `tests/test_law.py::test_an_agent_written_guard_
# is_not_law_without_an_approval` measures exactly that. A fixed date cannot
# be reached by anything written from here on, so the grandfathered set can
# only ever shrink.
#
# Compared against the record's own sealed `recorded_at` date, and a record
# with no readable date is NOT pre-gate (fail closed).
GATE_SHIPPED_DATE = "2026-09-18"


def _recorded_before_the_gate(record: dict[str, Any]) -> bool:
    day = str(record.get("recorded_at", ""))[:10]
    return len(day) == 10 and day < GATE_SHIPPED_DATE


def _migration_cutoff_of(record: dict[str, Any]) -> int:
    """The cutoff sequence a migration record carries, or 0 if it carries
    nothing readable. Never raises on a hand-mangled record: an unreadable
    cutoff grandfathers nothing, which is the fail-closed direction."""
    raw = (record.get("data") or {}).get("cutoff_seq")
    if isinstance(raw, bool) or not isinstance(raw, int) or raw <= 0:
        return 0
    return raw


def _is_migration_record(record: dict[str, Any]) -> bool:
    return (record.get("kind") == LAW_MIGRATION_KIND
            and record.get("subject") == LAW_MIGRATION_SUBJECT)


def migration_cutoff(archive: Any) -> int:
    """The highest grandfather cutoff this archive has recorded, or 0 when
    it has never been migrated. Read-only."""
    cutoff = 0
    for record in archive.read_events():
        if _is_migration_record(record):
            cutoff = max(cutoff, _migration_cutoff_of(record))
    return cutoff


def lesson_carries_authority(record: dict[str, Any], *, cutoff: int = 0) -> bool:
    """NS-2 (0.3.28 Plan 5 Task 2, fix round 1, B1): may this lesson's guard
    become compiled law at all?

    Three ways now, and the third is a one-time line under the past:
    `cutoff` is the grandfather sequence a migration record recorded (0 when
    the archive has never been migrated, which is the default and admits
    nothing extra). A lesson at or below it was written before the gate
    existed and keeps the standing it already had; a lesson above it is held
    to the two rules below exactly as designed, even when it is a fresh
    record on a subject the migration did grandfather.

    Two ways otherwise. Either the record carries APPROVAL LINEAGE - an
    `approval_seq` written by `godmode_lessons.approve`, which is the only
    code path that mints one and only mints it after comparing the promoter
    and the approver as fingerprints - or it was written with OPERATOR
    TRUST (`godmode_chronicle.record_writer`, sealed into the record at
    write time and covered by its own hash, so it cannot be back-filled).

    The rule stated plainly: *an agent's guard needs a second actor; an
    operator's guard is the second actor.* Before this, any process could
    `append("lesson", s, {"status": "active", "generalized_guard": ...})`
    and read its own sentence back out of `GODMODE-CODE-OF-LAW.md` on the
    next compile - self-legislation with no promotion, no approval and no
    trust, in the one file every session is instructed to obey. The
    operator carve-out is deliberate and named: NS-2's target is an AGENT
    legislating for itself, and an operator typing their own standing guard
    is already the highest trust the model has - `--standing` and the
    charter path would otherwise have to stage a two-actor dance against
    themselves.

    Not a status check: `LESSON_DORMANT_STATUSES` above answers "is this
    lesson still live", which is a different question and is asked
    separately. A retired lesson with a perfect approval chain still
    compiles nothing.
    """
    # Deferred: `godmode_chronicle` imports THIS module at its own module
    # level, so the dependency only runs one way at import time. By the time
    # any archive exists to read lessons out of, chronicle is in sys.modules.
    from .godmode_chronicle import TRUST_ORDER, record_trust

    data = record.get("data") or {}
    approval = data.get("approval_seq")
    if isinstance(approval, int) and not isinstance(approval, bool) and approval > 0:
        return True
    if record_trust(record) >= TRUST_ORDER["operator"]:
        return True
    return cutoff > 0 and int(record.get("sequence", 0)) <= cutoff


def _lesson_records_by_subject(
    archive: Any,
) -> tuple[dict[str, list[dict[str, Any]]], int, int]:
    """One pass over the archive: every `lesson` record grouped by subject
    in sequence order, the grandfather cutoff this archive has recorded,
    and the archive head sequence. The history is kept, not only the newest
    record, because `_standing_record` below has to look PAST a record that
    cannot carry authority to the one that still does."""
    by_subject: dict[str, list[dict[str, Any]]] = {}
    cutoff = 0
    head = 0
    for record in archive.read_events():
        head = max(head, int(record.get("sequence", 0)))
        if _is_migration_record(record):
            cutoff = max(cutoff, _migration_cutoff_of(record))
            continue
        if record.get("kind") != "lesson":
            continue
        by_subject.setdefault(str(record.get("subject", "")), []).append(record)
    for history in by_subject.values():
        history.sort(key=lambda record: int(record.get("sequence", 0)))
    return by_subject, cutoff, head


def _is_dormant(record: dict[str, Any]) -> bool:
    # Normalised the same way `Chronicle` stores and compares it
    # (`.strip().lower()`, godmode_chronicle.py's `_write_record` /
    # `_sync_enforce_index`) - a raw comparison read a `"Superseded"`
    # lesson as dormant here and active for enforcement, the same class of
    # reader/writer drift nit 7 already closed once.
    data = record.get("data") or {}
    return str(data.get("status", "active")).strip().lower() in LESSON_DORMANT_STATUSES


def _is_live_guarded(record: dict[str, Any]) -> bool:
    data = record.get("data") or {}
    return (not _is_dormant(record)
            and bool(str(data.get("generalized_guard") or "").strip()))


def _live_guarded_lesson_records(archive: Any) -> tuple[list[dict[str, Any]], int, int]:
    """The newest LIVE, GUARDED `lesson` record per subject (authority not
    yet asked about), the grandfather cutoff this archive has recorded, and
    the archive head sequence.

    Split out of `_guarded_lessons` (NS-2 fix round 2) because the migration
    writer needs exactly this population - what the law would carry if the
    gate were not there - and reading it twice, once with a different
    dedup, is how the two copies of `LESSON_DORMANT_STATUSES` drifted
    before.
    """
    by_subject, cutoff, head = _lesson_records_by_subject(archive)
    live = [history[-1] for history in by_subject.values()
            if _is_live_guarded(history[-1])]
    return live, cutoff, head


# The one dormant status that means "waiting for a second actor" rather
# than "this subject's guard is lifted". A `candidate` on a subject that
# already has a standing law is the documented conversion path
# (`_GRANDFATHER_NOTE`: re-record as a structured candidate, promote,
# approve) in flight; it is not a retirement, so it must not read as one.
_PENDING_STATUS = "candidate"


def _is_lift(record: dict[str, Any]) -> bool:
    """A record that says "this guard no longer stands": a dormant status
    other than `candidate` (retired, superseded), or a live record that
    dropped the guard. Whether it is ALLOWED to lift the standing law is
    `_standing_record`'s question, answered by trust."""
    data = record.get("data") or {}
    status = str(data.get("status", "active")).strip().lower()
    if status == _PENDING_STATUS:
        return False
    return _is_dormant(record) or not _is_live_guarded(record)


def _standing_record(
    history: list[dict[str, Any]], cutoff: int,
) -> tuple[dict[str, Any] | None, dict[str, Any] | None]:
    """Which record of a subject's history IS the law, and which newer
    record (if any) is waiting on approval to replace or lift it.

    Newest-wins dedup with the authority gate read on the newest record
    alone had a hole (0.3.28 release preflight): an agent's `law amend` on
    an operator's standing law wrote a newer record the gate refused, and
    the subject then compiled NOTHING - the operator's law vanished because
    an agent edited it, which is the opposite of what the gate exists for.
    So the standing record is the NEWEST record that is live, guarded and
    carries authority (`lesson_carries_authority`); every record after it
    is then read for what it tries to do:

    * an amendment (live, guarded, no authority) or a `candidate` is
      PENDING - the standing record stays the law and the compiled file
      names the pending sequence, never silently;
    * a lift (`retired`, `superseded`, or a guard dropped) counts only when
      its writer's trust is at least the standing record's
      (`record_trust`): an operator lifts anything, an agent lifts its own
      or another agent's law, and a lower-trust writer cannot lift what a
      higher-trust one set - the same rank rule the archive's single-writer
      close guard applies to `retired` (NS-11h), applied here to every lift
      word, because `superseded` is not a close there and would otherwise
      be a one-word way for an agent to de-legislate the operator. A lift
      that lacks the rank is pending like an amendment. A lift that has it
      ends the law, and nothing written after it revives the subject
      without authority of its own (the newest authorised record is
      searched for first, so a later approved or operator record does).
    """
    from .godmode_chronicle import record_trust

    standing_index = None
    for index in range(len(history) - 1, -1, -1):
        record = history[index]
        if _is_live_guarded(record) and lesson_carries_authority(record, cutoff=cutoff):
            standing_index = index
            break
    if standing_index is None:
        return None, None
    standing = history[standing_index]
    newer = history[standing_index + 1:]
    for record in newer:
        if _is_lift(record) and record_trust(record) >= record_trust(standing):
            return None, None
    return standing, (newer[-1] if newer else None)


def _guarded_lessons(archive: Any) -> list[dict[str, Any]]:
    """Every living guarded lesson admitted into the law, newest first.

    Dedup by subject, newest record wins (2026-08-29): a promotion retried
    after a parse error wrote the same law twice, and two 2026-08-11
    lessons had shared a subject since before the compiler existed - each
    rendered as its own law. One subject, one law, and appending a retired
    record now actually retires the law (the newest record is the subject's
    state, the same rule status remaining already follows) - including a
    GRANDFATHERED law: the retirement record is the subject's newest, it is
    dormant, and dormancy is read before authority is ever asked about, so
    retirement lifts a grandfathered guard exactly as it lifts any other.

    Newest-wins has one qualification since the 0.3.28 release preflight:
    a newest record that is merely PENDING (a candidate, or a guard with no
    authority) does not unseat the subject's standing law - see
    `_standing_record`. The law stays what it was, and `pending_amendment`
    names the record waiting on approval.
    """
    by_subject, cutoff, _head = _lesson_records_by_subject(archive)
    lessons = []
    for history in by_subject.values():
        # NS-2 fix round 1 (B1): the gate. Asked only of records that got
        # this far - a guardless or dormant lesson compiles nothing either
        # way, so neither pays for the trust lookup. Fix round 2: `cutoff`
        # is the one-time grandfather line (0 on an unmigrated archive).
        record, pending = _standing_record(history, cutoff)
        if record is None:
            continue
        data = record.get("data") or {}
        lessons.append({
            "sequence": int(record.get("sequence", 0)),
            "subject": str(record.get("subject", ""))[:120],
            "guard": str(data.get("generalized_guard") or "").strip(),
            "why": str(data.get("value", "")),
            "recorded_at": str(record.get("recorded_at", ""))[:10],
            "standing": bool(data.get("standing")),
            # Visible, not silent: this law is in the file only because it
            # predates the gate, and no second actor has ever approved it.
            "grandfathered": not lesson_carries_authority(record),
            # Visible, not silent, the other way: a newer record on this
            # subject is waiting on approval; until then this one binds.
            "pending_amendment": (
                int(pending.get("sequence", 0)) if pending is not None else None),
        })
    lessons.sort(key=lambda lesson: lesson["sequence"], reverse=True)
    return lessons


# I-1 (0.3.28 Plan 5 Task 4): guards that execute. A lesson may carry
# `enforce: {kind, predicate}` - the archive refuses a write of `kind`
# whose `data` matches `predicate`, the guard text standing in as the
# remedy. The grammar is deliberately three operators, nothing richer:
# `field == literal`, `field contains literal`, `field matches <regex>`,
# always read against the INCOMING record's `data` (never `evidence` or
# other top-level fields, and a dotted path such as `a.b` descends into
# nested dicts). A field the write never set never matches - an enforce
# rule refuses what a write says, not what it silently omitted.
ENFORCE_OPS: tuple[str, ...] = ("==", "contains", "matches")
_ENFORCE_FIELD_RE = re.compile(r"[A-Za-z0-9_]+(\.[A-Za-z0-9_]+)*")

# I-1 fix round 1 (Blocking 2): both bounds review-measured as missing. The
# literal is refused OVER this length at parse time (predicate authoring is
# rare and cheap to refuse loudly); the scanned field text is bounded at
# match time instead (see `enforce_predicate_matches`) because that side
# runs on every write of the guarded kind, not once at authoring. Fix round
# 3 (Blocking 2): a `matches` field over this length REFUSES the write
# fail-closed instead of being truncated-then-scanned - round 2's
# truncate-then-scan reintroduced the exact hazard round 1's docstring had
# named as the reason not to truncate (a refusal for a match the real value
# never contained; see `enforce_predicate_matches`). `contains`/`==` still
# truncate: truncation can only ever LOSE a `contains` match
# (`literal in text[:N]` implies `literal in text`), and `==` against a
# truncated prefix is unconditionally false for a literal no longer than
# `_ENFORCE_LITERAL_MAX`, same as an untruncated compare against a longer
# value always was.
_ENFORCE_LITERAL_MAX = 256
_ENFORCE_TEXT_MAX = 4096


class EnforceFieldTooLong(Exception):
    """Raised by `enforce_predicate_matches` when a `matches` predicate's
    scanned field exceeds `_ENFORCE_TEXT_MAX` characters (fix round 3,
    Blocking 2). NOT an `ArchiveError`, on purpose: `Chronicle.
    _enforced_refusal` swallows `ArchiveError` from this module to skip a
    predicate that no longer parses on a hand-edited archive, and this is
    the opposite case - a predicate that parses fine but cannot be
    evaluated safely against oversized data - so it must reach the caller
    and refuse the write, never be treated as "this rule does not apply."
    """

    def __init__(self, field: str) -> None:
        self.field = field
        super().__init__(
            f"field {field!r} is too long for an enforce predicate: shorten "
            "it or cite it as evidence")


# I-1 fix round 1 (Blocking 2), widened round 2, tightened round 3
# (Blocking 1): a conservative syntactic refusal against catastrophic
# backtracking. Round 1 only refused a quantified atom directly inside a
# group that is itself quantified (`(x+)+`, `(x*)*`); round 2 widened that
# to ANY quantifier following a `)`, whatever the group contains - but
# re-review measured that stacked quantified ATOMS (never inside a group at
# all) are polynomial and just as unusable at the 4,096-character cap:
# `a+a+a+a+X` took 44.6s at 200 scanned characters (~n^5.7) and did not
# finish in 45s at 4,096, run inside the write lock's 20s deadline. Round
# 2's own remedy text recommended exactly that construction.
#
# `matches` now accepts AT MOST ONE quantifier in the entire pattern -
# `+`, `*`, `?`, `{n}`, `{n,}`, or `{n,m}` - applied to a single atom or
# character class, never a group and never a second one anywhere else in
# the pattern (anchors and plain literals are free, and cost nothing: a
# fixed number of anchor/literal comparisons per scanned character). This
# is the bound the "bounded regex against bounded text" claim in
# `enforce_predicate_matches` rests on: one quantifier over at most
# `_ENFORCE_TEXT_MAX` (4,096) characters is at worst quadratic in that
# length on CPython's backtracking engine (`.*X` with no X: 0.075 s at
# 4,096; the slowest accepted shape measured, `(?=.*X)`, 0.26 s) - bounded
# and small, not linear. Two or more quantifiers - even two plain atoms,
# `a*a*b` - or an alternation inside a group (`(a|aa)` chained) can force
# that scan to be repeated once per position the earlier choice could have
# stopped at, which is exactly the polynomial/exponential blowup this
# refuses. Non-greedy forms (`+?`, `*?`) read as a second quantifier and
# are refused too.
#
# Deliberately NOT a general ReDoS detector (undecidable in general): a
# fast, syntax-only scan over the regex SOURCE text, never executed
# against user data, that counts quantifier occurrences and refuses at the
# first sign of more than one, or of one bound to a group. A quantifier
# hidden behind an escape (`\+`, `\)`) is not distinguished from a real one
# (the whole escaped pair is skipped, so it is never counted as either) -
# conservative, per the same ruling; a `?` immediately after an unescaped
# `(` is treated as the special-group opener it is (`(?:`, `(?=`, `(?!`,
# `(?i)`, `(?<name>`, `(?P<name>`, ...), not a quantifier, so those inline
# constructs do not eat the pattern's one allowed quantifier.
def _enforce_regex_quantifier_violation(pattern: str) -> str | None:
    """`None` when `pattern` carries at most one quantifier and it binds to
    an atom or character class, never a group; otherwise a short reason
    string for the refusal message."""
    in_class = False
    quantifier_seen = False
    depth = 0
    index = 0
    length = len(pattern)
    while index < length:
        char = pattern[index]
        if char == "\\":
            index += 2  # an escaped pair is never a quantifier or a class boundary
            continue
        if in_class:
            if char == "]":
                in_class = False
            index += 1
            continue
        if char == "[":
            in_class = True
            index += 1
            continue
        if char == "(":
            depth += 1
        elif char == ")":
            depth = max(0, depth - 1)
        elif char == "|" and depth > 0:
            # Re-review round 3: an ambiguous alternation inside a group
            # needs no quantifier at all to blow up - `(a|aa)` chained 42
            # times is under the literal cap, parses clean, and did not
            # finish in 90 s against 4,096 characters. Top-level branches
            # are each tried once; a grouped one can be re-entered per
            # position, so it is refused outright.
            return "alternates inside a group"
        preceding = pattern[index - 1] if index > 0 else ""
        if char == "?" and preceding == "(":
            index += 1  # `(?...)` - a special group opener, not a quantifier
            continue
        end = index
        if char in "+*?":
            end = index + 1
        elif char == "{":
            brace = re.match(r"\{\d+(,\d*)?\}", pattern[index:])
            if brace:
                end = index + brace.end()
        if end != index:
            if preceding == ")":
                return "quantifies a group"
            if quantifier_seen:
                return "carries more than one quantifier"
            quantifier_seen = True
            index = end
            continue
        index += 1
    return None

# I-1 fix round 1 (Blocking 3): a lesson's `enforce` may never target one of
# the gate's own audit-trail kinds. `record_refusal` (kind=refusal),
# every hook-side nudge/observation (kind=action), and C-8's checkpoints
# (kind=checkpoint) are all written by `writer == "hook"` - see the matching
# exemption in `Chronicle._enforced_refusal` (godmode_chronicle.py). That
# exemption alone stops a brick (a hook's own write is never refused), but
# an enforce lesson naming one of these kinds would still silently delete
# every OTHER writer's matching record with no signal the operator asked
# for it, so authoring one is refused here, loudly, with the reason named -
# the same "refuse now, not silently never fire" contract every other
# malformed `--enforce` already gets.
ENFORCE_FORBIDDEN_KINDS = frozenset({"refusal", "action", "checkpoint"})


def parse_enforce_predicate(predicate: str) -> dict[str, str]:
    """Parse `field == literal` / `field contains literal` / `field matches
    <regex>` into `{"field", "op", "literal"}`. Refuses (ArchiveError) a
    predicate with no recognised operator, an empty field or literal, a
    field that is not a plain dotted path, a literal over
    `_ENFORCE_LITERAL_MAX` characters, a `matches` literal that does not
    compile as a regex, or one that carries more than one quantifier or
    quantifies a group at all - `(x+)+`, `(a|aa)+`, `(x+){2,}`, `(ab)?`,
    `a+a+a+a+X`, `a*a*b`, `[ab]*[ab]*c`, whatever the shape (fix round 3,
    see `_enforce_regex_quantifier_violation`: AT MOST ONE quantifier is
    allowed anywhere in the pattern, and it must bind to a single atom or
    character class, never a group) - the same shape check runs whether the
    predicate arrives through `remember --enforce` or straight at
    `Chronicle.append`, so a malformed one is refused at write time no
    matter which caller wrote it."""
    from .godmode_errors import ArchiveError

    text = str(predicate or "").strip()
    if not text:
        raise ArchiveError("--enforce predicate must not be empty")
    # Leftmost operator, not longest-first (fix round 1, nit 6): a literal
    # such as "some text that contains a word" after "value == " used to be
    # mis-split on " contains " (checked first for being the longer marker),
    # producing a field ("value == some text that") that fails the field
    # regex and refuses a well-formed "==" predicate with a confusing
    # remedy. The FIRST operator marker to actually occur in the text is
    # the one the operator meant, no matter how long its name is.
    earliest: tuple[int, str] | None = None
    for op in ENFORCE_OPS:
        marker = f" {op} "
        position = text.find(marker)
        if position == -1:
            continue
        if earliest is None or position < earliest[0]:
            earliest = (position, op)
    if earliest is not None:
        op = earliest[1]
        field, _, literal = text.partition(f" {op} ")
        field, literal = field.strip(), literal.strip()
        if not field or not _ENFORCE_FIELD_RE.fullmatch(field):
            raise ArchiveError(
                f"--enforce predicate field {field!r} must be a dotted path "
                "of plain names (e.g. 'value' or 'import_verdict.kind')")
        if not literal:
            raise ArchiveError(
                f"--enforce predicate '{op}' needs a non-empty literal")
        if len(literal) > _ENFORCE_LITERAL_MAX:
            raise ArchiveError(
                f"--enforce predicate literal is {len(literal)} characters, "
                f"max {_ENFORCE_LITERAL_MAX} - put the detail in the guard "
                "text, not the match literal")
        if op == "matches":
            try:
                re.compile(literal)
            except re.error as exc:
                raise ArchiveError(
                    f"--enforce predicate regex {literal!r} does not compile: {exc}"
                ) from exc
            violation = _enforce_regex_quantifier_violation(literal)
            if violation is not None:
                raise ArchiveError(
                    f"--enforce predicate regex {literal!r} {violation} - "
                    "'matches' accepts AT MOST ONE quantifier in the whole "
                    "pattern ('+', '*', '?', '{n}', '{n,}', '{n,m}'), bound "
                    "to a single atom or character class, never a group: "
                    "'(x+)+', '(a|aa)+', '(x+){2,}', '(ab)?', 'a+a+a+a+X', "
                    "'a*a*b' and '[ab]*[ab]*c' are all refused, because a "
                    "second quantifier (grouped or not) can run "
                    "catastrophically or polynomially slowly and this match "
                    "runs inside the archive's write lock, stalling every "
                    "other writer; rewrite it with a single quantified atom "
                    "or character class (e.g. 'x+', '[a-z]{1,40}') instead, "
                    "or use 'field contains literal' if a substring test is "
                    "enough")
        return {"field": field, "op": op, "literal": literal}
    raise ArchiveError(
        "--enforce predicate must be 'field == literal', 'field contains "
        "literal', or 'field matches <regex>' (got " + repr(text) + ")")


def parse_enforce_spec(spec: str) -> dict[str, str]:
    """Parse `kind=<record kind>;predicate=<field op value>` into
    `{"kind", "predicate"}`, validating both halves so a malformed
    `--enforce` is refused at `remember` time rather than persisted and
    silently never firing. Split on the FIRST ';' only: the predicate half
    may itself contain ';' (rare, but a regex alternation could)."""
    from .godmode_errors import ArchiveError
    from .godmode_constants import EVENT_KINDS

    text = str(spec or "").strip()
    first, sep, rest = text.partition(";")
    if not sep:
        raise ArchiveError(
            "--enforce must be 'kind=<record kind>;predicate=<field op "
            "value>'")
    kind_key, kind_sep, kind = first.partition("=")
    predicate_key, predicate_sep, predicate = rest.partition("=")
    if kind_key.strip().lower() != "kind" or not kind_sep:
        raise ArchiveError("--enforce's first clause must be 'kind=<record kind>'")
    if predicate_key.strip().lower() != "predicate" or not predicate_sep:
        raise ArchiveError(
            "--enforce's second clause must be 'predicate=<field op value>'")
    kind = kind.strip()
    predicate = predicate.strip()
    if not kind or kind not in EVENT_KINDS:
        raise ArchiveError(f"--enforce kind {kind!r} is not a recognised record kind")
    if kind in ENFORCE_FORBIDDEN_KINDS:
        raise ArchiveError(
            f"--enforce kind {kind!r} is refused: {kind} is the gate's own "
            "audit trail, written by hooks on the operator's behalf "
            "(record_refusal, tripwire/usage/edit actions, checkpoints) - "
            "an enforce guard against it would silently drop those hooks' "
            "own records with no signal, since a hook's writes are exempt "
            "from enforcement and never refused themselves; target a kind "
            "an agent or operator writes directly instead")
    parse_enforce_predicate(predicate)  # raises on malformed; result unused here
    return {"kind": kind, "predicate": predicate}


def _enforce_field_value(data: dict[str, Any], field: str) -> tuple[Any, bool]:
    current: Any = data
    for part in field.split("."):
        if not isinstance(current, dict) or part not in current:
            return None, False
        current = current[part]
    return current, True


def _enforce_text(value: Any) -> str:
    if isinstance(value, str):
        return value
    if isinstance(value, (list, tuple)):
        return "\n".join(_enforce_text(item) for item in value)
    if value is None:
        return ""
    return str(value)


def enforce_predicate_matches(predicate: str, data: dict[str, Any]) -> bool:
    """True when `data` (a record's own `data` payload - never `evidence`
    or other top-level fields) matches `predicate`. A field the payload
    never set is never a match, dotted paths descend into nested dicts,
    and list/tuple values are matched against each stringified item
    joined by newlines so `contains`/`matches` can find one among several.

    A scanned field longer than `_ENFORCE_TEXT_MAX` characters is handled
    differently per operator (fix round 3, Blocking 2 - corrected from
    round 2's blanket truncate-then-scan): `contains` and `==` TRUNCATE to
    the first `_ENFORCE_TEXT_MAX` characters, unchanged from round 2, and
    that is safe for both - `literal in text[:N]` implies `literal in
    text`, so truncation can only ever LOSE a `contains` match, never
    invent one, and `==` against a truncated prefix is unconditionally
    false for a literal no longer than `_ENFORCE_LITERAL_MAX` compared to a
    longer value, same as an untruncated compare against a longer value
    always was. `matches` is different in kind, not degree: truncating
    first and then running the regex can INVENT a match the full value
    never had, not merely miss one - verified in re-review, `value matches
    TODO$` against `"x" * 4092 + "TODO" + "y" * 40` (a value that does not
    end in "TODO") matched once truncated to the first 4,096 characters,
    because truncation moved what the pattern anchors against. Round 1's
    docstring had already named this exact hazard as the reason not to
    truncate; round 2 dropped the sentence without solving it. So `matches`
    against an over-cap field raises `EnforceFieldTooLong` instead of
    guessing either direction - the write is refused, fail-closed, naming
    the field, rather than truncated-then-compared or silently passed.

    A single quantifier over a field within `_ENFORCE_TEXT_MAX` is at
    worst quadratic in that length - 0.26 s for the slowest accepted shape
    at the cap (see `_enforce_regex_quantifier_violation`, which is
    what keeps `matches` itself bounded once a field is short enough to be
    evaluated at all)."""
    parsed = parse_enforce_predicate(predicate)
    value, found = _enforce_field_value(data or {}, parsed["field"])
    if not found:
        return False
    text = _enforce_text(value)
    op, literal = parsed["op"], parsed["literal"]
    if len(text) > _ENFORCE_TEXT_MAX:
        if op == "matches":
            raise EnforceFieldTooLong(parsed["field"])
        text = text[:_ENFORCE_TEXT_MAX]
    if op == "==":
        return text == literal
    if op == "contains":
        return literal in text
    if op == "matches":
        return re.search(literal, text) is not None
    return False


def _delivered_seqs(archive: Any) -> set[int]:
    delivered: set[int] = set()
    for record in archive.read_events():
        if record.get("kind") == "action" and record.get("subject") == "laws-delivered":
            for seq in (record.get("data") or {}).get("law_seqs") or []:
                delivered.add(int(seq))
    return delivered


def top_laws(archive: Any, k: int) -> list[dict[str, Any]]:
    """The k newest laws, bounded for the brief's budget - plus every
    standing law, pinned ahead of them regardless of k. `dormant` means no
    delivery receipt has ever named this law - L3's decay input, flagged
    rather than silently carried. A standing lesson (`--standing`) is a
    guard the operator marked as enforcing, not advisory; a budget that
    drops it once k newer lessons arrive turns an enforcing guard into
    advice by attrition, which is the failure this pins against.
    """
    delivered = _delivered_seqs(archive)
    guarded = _guarded_lessons(archive)
    standing = [lesson for lesson in guarded if lesson["standing"]]
    rest = [lesson for lesson in guarded if not lesson["standing"]][: max(0, k)]
    return [
        {"subject": lesson["subject"], "guard": _flatten(lesson["guard"]),
         "seq": lesson["sequence"], "dormant": lesson["sequence"] not in delivered,
         "standing": lesson["standing"],
         "pending_amendment": lesson.get("pending_amendment")}
        for lesson in standing + rest
    ]


# NS-2 fix round 2: the grandfather marker, stated in the artifact rather
# than left for a reader to infer. A `[GRANDFATHERED]` law is in this file
# only because it predates the authority gate: no second actor has ever
# approved it, and the note below says exactly how to convert one. Same
# doctrine as the cap line under it - no silent anything.
_GRANDFATHER_NOTE = (
    "{count} law(s) below are marked [GRANDFATHERED]: they were recorded "
    "before `law compile` required a second actor, so nobody has ever "
    "approved them. They still bind, and they are counted by `godmode law "
    "hygiene` until they are converted. To convert one: re-record it as a "
    "structured candidate (`godmode remember --kind lesson --subject "
    "<subject> --status candidate`, carrying root_cause, correction, "
    "reflection, generalized_guard and refuted_by), run `godmode lessons "
    "promote <lesson-seq> --cite seq:<n> --rerun-hash <h>`, and have a "
    "DIFFERENT actor run `godmode lessons approve <promotion-seq> "
    "--rerun-hash <their own h>`. A guard that is wrong is retired instead "
    "(`godmode remember --kind lesson --subject <subject> --status "
    "retired`), which lifts it here on the next compile."
)


_PENDING_NOTE = (
    "{count} law(s) below carry [AMENDMENT PENDING seq:<n>]: a newer record "
    "on that subject was written without a second actor's approval, "
    "operator trust, or the trust to lift it, so it is not the law yet. The "
    "guard shown is the last one that carried authority, and it binds until "
    "one of: the operator re-issues the guard (`godmode law amend "
    "--as-operator`) or retires the law; or a NEW structured candidate is "
    "recorded on the same subject (`godmode remember --kind lesson "
    "--subject <subject> --status candidate` with root_cause, correction, "
    "reflection, generalized_guard and refuted_by), promoted with `godmode "
    "lessons promote`, and approved by a different actor with `godmode "
    "lessons approve`. The pending record itself is active, not a "
    "candidate, so it cannot be promoted; it is superseded by whichever of "
    "those lands."
)


# The compiled law file is shared with the project; the lesson it came from
# stays in the local archive. A citation of outside scholarship in a lesson's
# subject or why is kept there and not copied into the shared file (0.3.28:
# a law title named a preprint and every compile rewrote it).
_CITATION = re.compile(r"(?i)\barxiv[:\s/]|\bet\s+al\.")
_CITATION_SPAN = re.compile(r"(?i)\s*\([^)]*(?:\barxiv\b|\bet\s+al\.)[^)]*\)")


def _shared_title(lesson: dict[str, Any]) -> str:
    """The law's heading: its subject, or its guard's first clause when the
    subject cites outside scholarship."""
    subject = str(lesson["subject"])
    if not _CITATION.search(subject):
        return subject
    first = re.split(r"(?<=[.;])\s", _flatten(lesson["guard"]), maxsplit=1)[0]
    return _ellipsize(first.rstrip(".;"), 80)


def _shared_why(lesson: dict[str, Any]) -> str:
    why = _CITATION_SPAN.sub("", str(lesson["why"]))
    if _CITATION.search(why):
        return f"the reasoning cites outside sources; read it at seq:{lesson['sequence']} in the local archive"
    return why


def _render(laws: list[dict[str, Any]], dropped: int, cap: int) -> str:
    lines = [_HEADER]
    grandfathered = sum(1 for lesson in laws if lesson.get("grandfathered"))
    if grandfathered:
        lines.append(_GRANDFATHER_NOTE.format(count=grandfathered))
        lines.append("")
    pending = sum(1 for lesson in laws if lesson.get("pending_amendment"))
    if pending:
        lines.append(_PENDING_NOTE.format(count=pending))
        lines.append("")
    for number, lesson in enumerate(laws, 1):
        marks = "[ADVISORY]" + (
            "  [GRANDFATHERED]" if lesson.get("grandfathered") else "")
        if lesson.get("pending_amendment"):
            marks += f"  [AMENDMENT PENDING seq:{lesson['pending_amendment']}]"
        lines.append(f"## Law {number} - {_shared_title(lesson)}  {marks}")
        lines.append(f"Guard: {_flatten(lesson['guard'])}")
        lines.append(f"Why: {_ellipsize(_shared_why(lesson), WHY_CHARS)}")
        lines.append(
            f"Provenance: seq:{lesson['sequence']}, recorded {lesson['recorded_at']}")
        lines.append("")
    if dropped:
        lines.append(
            f"{dropped} older guarded lesson(s) beyond the cap of {cap} are not "
            "rendered here - raise the cap, or retire laws that no longer earn "
            "their place.")
        lines.append("")
    return "\n".join(lines)


_SKILL_BODY = f"""---
name: {SKILL_DIRNAME}
description: Use at the start of every session and before every new task - read {LAW_FILENAME} at the project root when it exists (the project's generated Code of Law; `godmode law compile` writes it), and follow its guards before acting. Not for writing new laws; do not use when {LAW_FILENAME} is absent.
---

# The project's Code of Law

Read `{LAW_FILENAME}` at the project root before substantive work, if it exists. A project with no guarded lessons yet has no file, and that is not an error: `godmode law compile` writes it once at least one lesson carries a guard. Every law
was recorded by this project from its own corrections and carries its
archive provenance. Follow each law's guard; when one seems wrong, say so
and retire the underlying lesson (`godmode lessons`) rather than silently
ignoring it. Regenerate after new lessons with `godmode law compile`.
"""


# Obligation 4521: a candidate was built from a passage the operator
# explicitly said to disregard. A prompt that carries a disregard marker
# feeds neither detector - the operator already ruled on it.
_DISREGARD_MARKERS = ("ignore this", "disregard this", "by mistake",
                      "entered here by mistake")


_CORRECTION_MARKERS = frozenset({
    "wrong", "again", "missed", "incorrect", "mistake", "revert", "undo",
})
_CORRECTION_THRESHOLD = 2

# loop-engineering's reliability discipline, absorbed 2026-08-28: nothing
# escalates on one observation. A candidate cluster is promotable only after
# the same correction recurs in this many DISTINCT sessions.
PROMOTION_SESSIONS = 3


_HYGIENE_NEGATION = re.compile(
    r"\b(?:not|never|no|don't|cannot|must\s+not|avoid|without)\b", re.IGNORECASE
)
_HYGIENE_STOPWORDS = frozenset(
    "the a an and or of to in for with must never always not no every any "
    "this that from by on at is are be do".split()
)


def _hygiene_terms(text: str) -> set[str]:
    return {
        token for token in re.findall(r"[a-z][a-z-]{3,}", text.lower())
        if token not in _HYGIENE_STOPWORDS
    }


def _archived_candidate_seqs(archive: Any) -> set[int]:
    """Every candidate sequence a `lesson_candidate` shelf note has already
    taken out of the live set - `shelve_oldest_candidates` and
    `law_candidates` both skip these, the same way both already skip a
    promoted or dismissed one."""
    archived: set[int] = set()
    for record in archive.read_events():
        if record.get("kind") != "lesson_candidate":
            continue
        for seq in (record.get("data") or {}).get("archived_seqs") or []:
            try:
                archived.add(int(seq))
            except (TypeError, ValueError):  # godmode: swallow-ok: a malformed cite names nothing to archive
                continue
    return archived


def shelve_oldest_candidates(archive: Any) -> dict[str, Any]:
    """NS-2: bound the LIVE candidate set on two axes - count
    (`MAX_CANDIDATES`) and combined text (`MAX_CANDIDATE_CHARS`) - never
    unbounded (an unbounded candidate set is the named failure mode this
    guards against).

    Never chain-breaking: nothing is deleted or rewritten (the archive is
    append-only). Over either cap, the OLDEST live candidates are named in
    one `lesson_candidate` shelf note; `law_candidates` and this
    function's own next call both treat a shelved sequence as no longer
    live, the same way they already treat a promoted or dismissed one.
    Idempotent - a call that finds nothing over cap writes nothing.

    Fix round 1 (M3): `law_candidates` now actually honours the note. It
    did not before, so a shelved candidate still clustered, still counted
    toward `occurrences`/`distinct_sessions`, and was still promotable -
    the cap bought nothing but its own idempotence while this docstring
    claimed a bound that had no reader.

    NOT named "rotate" (fix round 1, merge review): NS-11e's
    `Chronicle.rotate_to_cold` genuinely MOVES records into a cold segment.
    This only appends a note naming them. Two meanings for one word, in one
    archive, is how an operator comes to believe their candidates were
    moved somewhere they can no longer be read.
    """
    from .godmode_lessons import MAX_CANDIDATE_CHARS, MAX_CANDIDATES

    archived = _archived_candidate_seqs(archive)
    live = [
        record for record in archive.read_events()
        if record.get("kind") == "lesson"
        and str((record.get("data") or {}).get("status")) == "candidate"
        and int(record.get("sequence", 0)) not in archived
    ]
    live.sort(key=lambda record: int(record.get("sequence", 0)))
    import json as _json

    def _chars(record: dict[str, Any]) -> int:
        return len(_json.dumps(record.get("data") or {}, sort_keys=True))

    archive_count = max(0, len(live) - MAX_CANDIDATES)
    remaining = live[archive_count:]
    remaining_chars = sum(_chars(record) for record in remaining)
    while remaining_chars > MAX_CANDIDATE_CHARS and remaining:
        removed = remaining.pop(0)
        archive_count += 1
        remaining_chars -= _chars(removed)
    to_archive = live[:archive_count]
    if not to_archive:
        return {"archived": 0, "live": len(live)}
    seqs = [int(record["sequence"]) for record in to_archive]
    archive.append(
        "lesson_candidate", "candidate-shelf",
        # `archived_count` is redundant with `len(archived_seqs)` on the
        # stored record and deliberately so (fix round 1, nit 6): the
        # compressed brief mask keeps the COUNT, because a mask exists to
        # bound and a 200-entry sequence list entering a brief verbatim is
        # the opposite of bounding. The full list stays here, in the
        # archive, reachable by the `reconstruct` seq the mask already
        # prints.
        {"archived_seqs": seqs, "archived_count": len(seqs),
         "reason": f"shelved over MAX_CANDIDATES={MAX_CANDIDATES}/"
                   f"MAX_CANDIDATE_CHARS={MAX_CANDIDATE_CHARS}"},
        evidence=[f"seq:{seq}" for seq in seqs],
    )
    return {"archived": len(seqs), "live": len(live) - len(seqs)}


def hygiene(archive: Any) -> dict[str, Any]:
    """Maintenance pass over the living laws. Names candidates; never retires.

    NOT purely a scan, and the CLI help now says so too (fix round 1, nit
    1): this pass also bounds the live candidate set, which appends ONE
    `lesson_candidate` shelf note when that set is over cap. It is the only
    write the pass makes, it deletes nothing, and it is reported under
    `shelved_candidates` rather than as a finding - but a verb documented
    as a read-only scan that quietly mutates the archive is exactly the
    surprise this project refuses everywhere else.

    Four checks, each about a different way a ratchet rots: a law with no
    recorded origin cannot be re-validated when the world changes; two
    active laws sharing their subject matter with opposite polarity are a
    disagreement waiting for a release to expose it; a law whose guard
    a pin now enforces mechanically is a retirement candidate - prose
    duplicating a sensor is debt, not protection; and a candidate cluster
    that has recurred for the ladder's own promotion bar (NS-2) with no
    promotion feeding it is named, never auto-promoted (a guard is
    reviewed prose). (Staleness and dormancy already live in `law
    debrief`; this pass does not repeat them.)
    """
    lessons = _guarded_lessons(archive)
    findings: list[dict[str, Any]] = []

    for cluster in law_candidates(archive):
        if cluster["promotable"]:
            findings.append({
                "check": "stale-candidate",
                # Fix round 1 (nit 2): every flag the parser makes
                # required is in the printed remedy. `--guard` and
                # `--subject` are required alongside `--candidate`, so the
                # old line exited 2 exactly as pasted, and a remedy that
                # does not run is not a remedy.
                "detail": f"candidate cluster at seq:{cluster['first_seq']} has "
                          f"recurred in {cluster['distinct_sessions']} distinct "
                          "session(s) with no promotion feeding it - `law "
                          f"promote --candidate {cluster['first_seq']} --guard "
                          "<the reviewed guard> --subject <subject>` or dismiss "
                          "it (`remember --kind lesson --subject <subject> "
                          "--status retired`)",
            })

    # NS-2 fix round 2: the grandfathered set is a debt to be worked down,
    # not a permanent class. One finding, naming the count and the two ways
    # out, so an operator can see it shrinking instead of discovering years
    # later that a third of the law was never approved by anyone.
    grandfathered = [lesson for lesson in lessons if lesson.get("grandfathered")]
    if grandfathered:
        findings.append({
            "check": "grandfathered-law",
            "detail": f"{len(grandfathered)} law(s) predate the authority gate "
                      "and have never been approved by a second actor (seq:"
                      + ", seq:".join(str(lesson["sequence"])
                                      for lesson in grandfathered[:10])
                      + (", ..." if len(grandfathered) > 10 else "")
                      + ") - promote and approve each one (`godmode lessons "
                        "promote <lesson-seq> --cite seq:<n> --rerun-hash <h>`, "
                        "then a DIFFERENT actor runs `godmode lessons approve "
                        "<promotion-seq> --rerun-hash <h>`), or retire the ones "
                        "that no longer earn their place",
        })

    for lesson in lessons:
        if not str(lesson.get("why", "")).strip():
            findings.append({
                "check": "no-recorded-origin",
                "detail": f"law '{lesson['subject']}' (seq:{lesson['sequence']}) "
                          "records no originating failure; add the why, or retire it",
            })

    terms = {lesson["sequence"]: _hygiene_terms(lesson["guard"]) for lesson in lessons}
    for i, first in enumerate(lessons):
        for second in lessons[i + 1:]:
            shared = terms[first["sequence"]] & terms[second["sequence"]]
            if len(shared) < 3:
                continue
            polarity_first = bool(_HYGIENE_NEGATION.search(first["guard"]))
            polarity_second = bool(_HYGIENE_NEGATION.search(second["guard"]))
            if polarity_first != polarity_second:
                findings.append({
                    "check": "contradictory-pair",
                    "detail": f"laws '{first['subject']}' (seq:{first['sequence']}) and "
                              f"'{second['subject']}' (seq:{second['sequence']}) share "
                              f"{len(shared)} terms with opposite polarity; one of them "
                              "is wrong, or one needs a scope clause",
                })

    checks = [
        (str(record.get("subject", "")),
         _hygiene_terms(str(record.get("subject", "")) + " "
                        + str((record.get("data") or {}).get("value", ""))))
        for record in archive.read_events()
        if record.get("kind") == "checklist"
    ]
    for lesson in lessons:
        for check_subject, check_terms in checks:
            if len(terms[lesson["sequence"]] & check_terms) >= 3:
                findings.append({
                    "check": "sensor-superseded",
                    "detail": f"law '{lesson['subject']}' (seq:{lesson['sequence']}) "
                              f"overlaps check '{check_subject}'; a mechanically "
                              "enforced guard no longer needs its prose twin - "
                              "retirement candidate",
                })
                break

    return {
        "laws_scanned": len(lessons),
        "grandfathered_unapproved": len(grandfathered),
        "findings": findings,
        "verdict": "clean" if not findings else "candidates-found",
        "shelved_candidates": shelve_oldest_candidates(archive),
    }


def record_correction_candidate(archive: Any, prompt: str, *,
                                session: str | None = None) -> dict[str, Any] | None:
    """The operator-correction detector (Sprint L2, decision 4114).

    A correction-shaped prompt - at least two distinct correction markers -
    writes a law CANDIDATE: a lesson with status "candidate", carrying the
    prompt's keywords and digest, never its sentence (the 4018 privacy
    decision holds here too). A candidate has no guard, so `law compile`
    never renders it; review drafts the guard, the ladder (L3) promotes it.
    Returns None for an ordinary prompt, a secret-shaped one, or an empty
    one - the detector is quiet by contract.
    """
    from .godmode_requests import _keywords, digest
    from .godmode_sentinel import find_secret_shapes

    flattened = " ".join(str(prompt).split())
    if not flattened or find_secret_shapes(flattened):
        return None
    if any(marker in flattened.lower() for marker in _DISREGARD_MARKERS):
        return None
    words = {w.lower() for w in flattened.replace(",", " ").split()}
    markers = sorted(_CORRECTION_MARKERS & words)
    if len(markers) < _CORRECTION_THRESHOLD:
        return None
    identifier = digest(flattened)
    return archive.append(
        "lesson",
        f"correction:{identifier[:12]}",
        {
            "status": "candidate",
            "value": "operator corrected the agent (counts only); draft a guard "
                     "at review, promote via the ladder",
            "keywords": sorted(_keywords(flattened))[:24],
            "markers": markers,
            "session": session,
            "digest": identifier,
        },
        evidence=[],
    )


_INSTRUCTION_PHRASES = ("from now on", "going forward", "every time",
                        "each time", "in every", "make sure you always")
_INSTRUCTION_WORDS = frozenset({"always", "never", "whenever"})
# S11-E (two live chat-noise captures 2026-08-29, e.g. "whenever ready: 9
# fragments ..."): a standing rule has a marker AND an imperative verb close
# behind it; a marker floating in conversation does not.
_INSTRUCTION_VERBS = frozenset({
    "run", "include", "record", "keep", "use", "check", "preview", "write",
    "add", "grade", "read", "cite", "update", "close", "open", "test",
    "verify", "review", "follow", "state",
})


def _verb_follows_marker(low: str, hit: str) -> bool:
    index = low.find(hit)
    if index < 0:
        return False
    tail = low[index + len(hit):].split()
    window = {token.strip(".,;:!?\"'()") for token in tail[:5]}
    return bool(window & _INSTRUCTION_VERBS)


def record_instruction_candidate(archive: Any, prompt: str, *,
                                 session: str | None = None) -> dict[str, Any] | None:
    """S6 (obligation 4435): the FIRST telling, not the second.

    Field report 2026-08-28: an operator's standing instruction lived in
    harness memory godmode cannot read, and was dropped for three reports;
    the correction detector only fires when the operator has to say it
    AGAIN. An instruction-shaped prompt - a standing-rule marker like
    "always"/"from now on" - becomes a candidate on first utterance, same
    privacy contract as corrections (keywords and digest, never the
    sentence). An explicit directive is stronger evidence than an inferred
    correction, so its cluster is promotable after ONE session instead of
    the correction ladder's three; the guard is still reviewed prose at
    promotion time.
    """
    from .godmode_requests import _keywords, digest
    from .godmode_sentinel import find_secret_shapes

    flattened = " ".join(str(prompt).split())
    if not flattened or find_secret_shapes(flattened):
        return None
    low = flattened.lower()
    if any(marker in low for marker in _DISREGARD_MARKERS):
        return None
    if len(low.split()) < 4:
        return None
    words = {w.strip(".,;:!?") for w in low.split()}
    # S11-E fix within the fix: check EVERY matching marker for a following
    # imperative verb, not only the first - "always include X in every
    # report" matches the phrase "in every" first, whose window holds no
    # verb, while "always" a few words earlier does.
    hits = [phrase for phrase in _INSTRUCTION_PHRASES if phrase in low]
    hits += [w for w in sorted(_INSTRUCTION_WORDS) if w in words]
    if not hits:
        return None
    hit = next((h for h in hits if _verb_follows_marker(low, h)), None)
    if hit is None:
        # No marker has an imperative verb behind it: conversation, not a
        # standing rule (S11-E) - the live false captures all fail here.
        return None
    identifier = digest(flattened)
    return archive.append(
        "lesson",
        f"instruction:{identifier[:12]}",
        {
            "status": "candidate",
            "origin": "instruction",
            "value": "operator stated a standing instruction (counts only); "
                     "draft a guard at review - promotable after one session",
            "keywords": sorted(_keywords(flattened))[:24],
            "markers": [hit],
            "session": session,
            "digest": identifier,
        },
        evidence=[],
    )


def law_candidates(archive: Any) -> list[dict[str, Any]]:
    """Candidates clustered read-time by keyword identity, so a repeated
    correction increments a counter instead of splitting the promotion
    ladder's own evidence across duplicates (dedup-or-increment)."""
    clusters: dict[frozenset[str], dict[str, Any]] = {}
    # A promoted cluster is consumed (2026-08-29): promotion appends the
    # law but left the candidate records standing, so the cluster stayed
    # "promotable" forever and invited a second, duplicate promotion.
    promoted: set[int] = set()
    for record in archive.read_events():
        if record.get("kind") != "lesson":
            continue
        origin = (record.get("data") or {}).get("promoted_from")
        if origin is not None:
            promoted.add(int(origin))
    dismissed: dict[str, bool] = {}
    for record in archive.read_events():
        if record.get("kind") == "lesson":
            dismissed[str(record.get("subject", ""))] = (
                str((record.get("data") or {}).get("status")) == "retired")
    # NS-2 fix round 1 (M3): a SHELVED candidate is no longer live. Without
    # this, the cap `shelve_oldest_candidates` enforces bounded nothing any
    # reader consulted - shelved records still clustered, still counted
    # toward the promotion ladder's own recurrence bar, and were still
    # promotable. A cap that buys only its own idempotence is a claim its
    # docstring makes and its code does not keep.
    shelved = _archived_candidate_seqs(archive)
    for record in archive.read_events():
        if record.get("kind") != "lesson":
            continue
        data = record.get("data") or {}
        if str(data.get("status")) != "candidate":
            continue
        if int(record.get("sequence", 0)) in shelved:
            continue
        if dismissed.get(str(record.get("subject", ""))):
            # S11 follow-up: a candidate whose subject was later retired is
            # DISMISSED - the pre-precision chat-noise captures needed a way
            # out that was not promotion.
            continue
        key = frozenset(str(k) for k in (data.get("keywords") or []))
        if not key:
            continue
        cluster = clusters.setdefault(key, {
            "keywords": sorted(key), "occurrences": 0, "sessions": set(),
            "first_seq": int(record.get("sequence", 0)),
            "origin": "correction",
        })
        if str(data.get("origin") or "") == "instruction":
            cluster["origin"] = "instruction"
        cluster["occurrences"] += 1
        cluster["last_seq"] = int(record.get("sequence", 0))
        session = data.get("session")
        if session:
            cluster["sessions"].add(str(session))
    ranked = []
    for cluster in clusters.values():
        if cluster["first_seq"] in promoted:
            continue
        cluster["distinct_sessions"] = len(cluster.pop("sessions"))
        # An explicit standing instruction promotes after one session; an
        # inferred correction still climbs the three-session ladder.
        needed = 1 if cluster.get("origin") == "instruction" else PROMOTION_SESSIONS
        cluster["promotable"] = cluster["distinct_sessions"] >= needed
        ranked.append(cluster)
    ranked.sort(key=lambda c: (-c["occurrences"], c["first_seq"]))
    return ranked


def promote_candidate(archive: Any, first_seq: int, *, guard: str,
                      subject: str) -> dict[str, Any]:
    """Promote a candidate cluster into a `lesson_promotion` - NOT directly
    into a law (0.3.28 Plan 5 Task 2: the ladder now feeds the same
    approval-gated pipeline `lessons promote`/`lessons approve` use). The
    guard is still REVIEWED prose written here, at promotion time (a
    candidate carries keywords, never a sentence worth enshrining
    verbatim), and the ladder still holds: below PROMOTION_SESSIONS
    distinct sessions, promotion is refused rather than discouraged.

    What changed: the freshly-authored lesson lands as a CANDIDATE (the
    same dormant status any other unapproved structured lesson carries),
    synthesized into NS-10j's five structured fields from the cluster's own
    evidence, then immediately cited into a `lesson_promotion` naming this
    same actor. It compiles into the law only once a DIFFERENT actor runs
    `godmode lessons approve <promotion-seq> --rerun-hash <h>` with a
    different rerun_hash than the one synthesized below - the promotion by
    itself never grants an advisory guard the way a direct `remember --kind
    lesson --status active` write still can (HARD enforcement stays with
    the charter; the ladder is ADVISORY, both before and after this task).
    """
    import hashlib

    from .godmode_errors import ArchiveError
    from .godmode_lessons import promote as lessons_promote

    guard = " ".join(str(guard).split())
    subject = str(subject).strip()
    if not guard or not subject:
        raise ArchiveError("Promotion needs --guard and --subject, both non-empty")
    cluster = next(
        (c for c in law_candidates(archive) if c["first_seq"] == int(first_seq)), None)
    if cluster is None:
        raise ArchiveError(
            f"No candidate cluster starts at seq {first_seq}; `law candidates` lists them")
    if not cluster["promotable"]:
        raise ArchiveError(
            f"Cluster at seq {first_seq} has recurred in {cluster['distinct_sessions']} "
            f"distinct session(s); the ladder requires {PROMOTION_SESSIONS} - "
            "reliability first, promotion second")
    keyword_text = ", ".join(cluster["keywords"][:10])
    lesson = archive.append(
        "lesson", subject,
        {
            "status": "candidate",
            "value": ("promoted from a correction cluster (keywords: "
                      + keyword_text + ")"),
            "generalized_guard": guard,
            "root_cause": f"a {cluster['origin']} recurred across "
                          f"{cluster['distinct_sessions']} distinct sessions "
                          f"(keywords: {keyword_text})",
            "correction": guard,
            "reflection": f"the cluster at seq:{cluster['first_seq']} repeated "
                          f"{cluster['occurrences']} time(s) before this guard "
                          "was reviewed and written",
            "refuted_by": "the same correction recurs again after this guard "
                          "is delivered",
            "promoted_from": cluster["first_seq"],
            "occurrences": cluster["occurrences"],
            "distinct_sessions": cluster["distinct_sessions"],
        },
        evidence=[f"seq:{cluster['first_seq']}", f"seq:{cluster['last_seq']}"],
    )
    rerun_hash = hashlib.sha256(
        f"ladder:{cluster['first_seq']}:{cluster['last_seq']}:{guard}".encode("utf-8")
    ).hexdigest()
    promotion = lessons_promote(
        archive, lesson["sequence"],
        cite=[f"seq:{cluster['first_seq']}", f"seq:{cluster['last_seq']}"],
        rerun_hash=rerun_hash,
    )
    return {**lesson, "promotion": promotion}


def debrief(archive: Any) -> dict[str, Any]:
    """The amendment loop (S10; loopy 4112's adopted-but-unbuilt half).

    Reads the archive once and answers, per law: how often was it DELIVERED
    (receipts), was it ever CITED (a later record naming its seq), and did
    the SAME correction recur AFTER a delivery (the law was shown and the
    behaviour repeated - a law that is not working). Recommendations are
    triaged the maintainer-orchestrator way: promoting a ready candidate is
    autonomous (the ladder already gates it); amending or retiring a law is
    needs-operator, because a guard is reviewed prose. The report states
    its own read window and stopping reason (loop-engineering's honest
    stops), and a counts-only receipt is appended so the next debrief
    starts where this one ended and staleness is measurable.
    """
    records = archive.read_events()
    last_debrief = 0
    for record in records:
        if record.get("kind") == "action" and record.get("subject") == "law-debrief":
            last_debrief = int(record.get("sequence", 0))
    laws = _guarded_lessons(archive)
    delivered: dict[int, int] = {}
    last_delivery: dict[int, int] = {}
    for record in records:
        if record.get("kind") == "action" and record.get("subject") == "laws-delivered":
            for seq in (record.get("data") or {}).get("law_seqs") or []:
                delivered[int(seq)] = delivered.get(int(seq), 0) + 1
                last_delivery[int(seq)] = int(record.get("sequence", 0))
    cited: dict[int, int] = {}
    for record in records:
        for reference in record.get("evidence") or []:
            text = str(reference)
            if text.startswith("seq:"):
                try:
                    cited[int(text[4:])] = cited.get(int(text[4:]), 0) + 1
                except ValueError:  # godmode: swallow-ok: best-effort read: the failure is the non-event here
                    pass
    from .godmode_sources import _salient_words

    candidates = [r for r in records
                  if r.get("kind") == "lesson"
                  and str((r.get("data") or {}).get("status")) == "candidate"]
    entries = []
    amend, retire = [], []
    for law in laws:
        seq = law["sequence"]
        vocabulary = _salient_words(f"{law['subject']} {law['guard']}")
        recurrences = [
            int(c.get("sequence", 0)) for c in candidates
            if int(c.get("sequence", 0)) > last_delivery.get(seq, 0)
            and last_delivery.get(seq)
            and len(_salient_words(" ".join(
                str(k) for k in (c.get("data") or {}).get("keywords") or []))
                & vocabulary) >= 3
        ]
        entry = {
            "seq": seq,
            "subject": law["subject"][:80],
            "delivered": delivered.get(seq, 0),
            "cited": cited.get(seq, 0),
            "recurred_after_delivery": recurrences[:5],
        }
        if len(recurrences) >= 2:
            entry["recommendation"] = "amend-guard"
            amend.append(entry)
        elif delivered.get(seq, 0) >= 3 and not cited.get(seq) and not recurrences:
            entry["recommendation"] = "retire-candidate"
            retire.append(entry)
        else:
            entry["recommendation"] = "keep"
        entries.append(entry)
    promotable = [c["first_seq"] for c in law_candidates(archive) if c["promotable"]]
    receipt = archive.append("action", "law-debrief", {
        "window": [last_debrief, int(records[-1]["sequence"]) if records else 0],
        "laws": len(laws), "amend": len(amend), "retire": len(retire),
        "promotable": len(promotable),
    }, evidence=[])
    return {
        "window": {"from_seq": last_debrief,
                   "to_seq": int(records[-1]["sequence"]) if records else 0},
        "stopping_reason": "window-exhausted",
        "laws": entries,
        "autonomous": {"promote_ready": promotable,
                       "note": "the ladder already gates these; `law promote` acts"},
        "needs_operator": {
            "amend_guard": [e["seq"] for e in amend],
            "retire_candidate": [e["seq"] for e in retire],
            "note": "a guard is reviewed prose - amend by appending a lesson "
                    "with the same subject (newest record wins), retire by "
                    "appending status retired",
        },
        "receipt_seq": receipt["sequence"],
    }


_DEBRIEF_STALE_AFTER = 300


def debrief_status(archive: Any) -> dict[str, Any]:
    """S11-A: the meta-loop's own staleness gauge. The first live debrief ran
    2026-08-29 and nothing would have prompted a second - now `law show` and
    the brief carry how many records have landed since the last receipt."""
    records = archive.read_events()
    last = 0
    for record in records:
        if record.get("kind") == "action" and record.get("subject") == "law-debrief":
            last = int(record.get("sequence", 0))
    latest = int(records[-1]["sequence"]) if records else 0
    since = latest - last if last else latest
    return {
        "last_receipt_seq": last or None,
        "records_since": since,
        "stale": last == 0 or since > _DEBRIEF_STALE_AFTER,
    }


def amend_law(archive: Any, law_seq: int, guard: str, *,
              as_operator: bool = False,
              operator_verified: bool | None = None) -> dict[str, Any]:
    """S11-D: execute a debrief amendment without hand-crafted appends.

    Appends a lesson with the SAME subject as the law at `law_seq` carrying
    the new reviewed guard. Refuses an empty guard, an unknown sequence,
    and a subject whose current state is retired or candidate - amendment
    is for living laws.

    Whether the amendment IS the law from here on is the authority gate's
    question, not this verb's (`lesson_carries_authority`): written with
    operator trust (`as_operator`, verified the way every other operator
    write is), it binds on the next compile; written by an agent, it is
    PENDING and the prior authorised guard stays in force until a second
    actor approves it - `_standing_record` has the rule. The returned
    record's `pending` says which happened, so the caller never has to
    infer it from a compile."""
    from .godmode_errors import ArchiveError

    guard = " ".join(str(guard).split())
    if not guard:
        raise ArchiveError("Amendment needs a non-empty reviewed guard")
    target = None
    latest_by_subject: dict[str, dict[str, Any]] = {}
    for record in archive.read_events():
        if record.get("kind") != "lesson":
            continue
        latest_by_subject[str(record.get("subject", ""))] = record
        if int(record.get("sequence", 0)) == int(law_seq):
            target = record
    if target is None:
        raise ArchiveError(f"No lesson record at seq {law_seq}")
    subject = str(target.get("subject", ""))
    current = latest_by_subject.get(subject) or {}
    current_data = current.get("data") or {}
    status = str(current_data.get("status", "active"))
    if status in ("retired", "candidate"):
        raise ArchiveError(
            f"'{subject[:60]}' is {status}; amendment is for living laws")
    amended: dict[str, Any] = {
        "status": "active",
        "generalized_guard": guard,
        "value": f"amended from seq {int(law_seq)} (S11 law amend)",
        "amended_from": int(law_seq),
    }
    # Newest-wins dedup (by subject) means this append IS the law from here
    # on - a standing law's flag lives only on the record being superseded,
    # so an amendment that dropped it would silently un-pin a law the
    # operator marked enforcing, while trying only to reword its guard.
    if bool(current_data.get("standing")):
        amended["standing"] = True
    # Fix round 2 (Blocking 3): the same principle as `standing`, and it
    # matters more, because dropping it does not just un-pin a law - it
    # trips `Chronicle._refuse_incomplete_supersession`. That guard refuses
    # ANY `lesson` append on a subject with an active `enforce` unless the
    # new record either reaffirms `enforce` or moves to a dormant status,
    # so before this an amendment on an enforcing law was refused outright,
    # with no way for this verb to comply - `amend_law` builds `amended`
    # from scratch and never carried `enforce` forward. Carrying it here
    # keeps the amendment doing what it says: reword the guard, not
    # silently disarm it.
    current_enforce = current_data.get("enforce")
    if isinstance(current_enforce, dict):
        amended["enforce"] = current_enforce
    record = archive.append(
        "lesson", subject, amended,
        evidence=[f"seq:{int(law_seq)}"],
        as_operator=as_operator, operator_verified=operator_verified,
    )
    # A fresh record always sits above any grandfather cutoff, so the gate
    # with no cutoff is exact here.
    return {**record, "pending": not lesson_carries_authority(record)}


def record_delivery(archive: Any, laws: list[dict[str, Any]], *,
                    session: str | None = None) -> dict[str, Any] | None:
    """The delivery receipt: which laws the brief carried, counts only.

    The denominator (loopy's receipts, via the L2 spec): without a record
    of delivery, "violated 0" cannot be told apart from "never seen".
    """
    if not laws:
        return None
    return archive.append(
        "action",
        "laws-delivered",
        {
            "delivered": len(laws),
            "law_seqs": [int(law.get("seq", 0)) for law in laws],
            "session": session,
        },
        evidence=[],
    )


_PROVENANCE = re.compile(r"^Provenance: seq:(\d+),", re.MULTILINE)


def fresh_laws(archive: Any, project: Path | str) -> list[dict[str, Any]]:
    """Guarded lessons the compiled law file does not carry yet.

    Knowledge recorded at the moment of discovery is load-bearing NOW, not
    after the next compile: this overlay reads the law file's own
    provenance lines and returns every living guarded lesson missing from
    them, marked fresh-uncompiled. Advisory by construction - the overlay
    feeds pre-action advisories only and no gate verdict reads it. No law
    file at all means every guarded lesson is fresh.
    """
    law_file = Path(project) / LAW_FILENAME
    compiled: set[int] = set()
    if law_file.is_file():
        compiled = {
            int(seq) for seq in _PROVENANCE.findall(
                law_file.read_text(encoding="utf-8"))
        }
    return [
        {"subject": lesson["subject"],
         "guard": _flatten(lesson["guard"]),
         "seq": lesson["sequence"],
         "marker": "fresh-uncompiled"}
        for lesson in _guarded_lessons(archive)
        if lesson["sequence"] not in compiled
    ]


def grandfather_pre_gate_lessons(archive: Any) -> dict[str, Any] | None:
    """NS-2 fix round 2 (the 0.3.28 upgrade blocker): draw the one-time line
    under an archive written before the authority gate existed. Returns the
    migration record's summary, or None when there is nothing to migrate or
    the archive already carries a migration record.

    WHY A RECORD AND NOT A FLAG. The gate (`lesson_carries_authority`) is
    right: an agent's guard needs a second actor. But it was added to a
    reader, not to a writer, so it applies retroactively to every lesson
    ever recorded - and every one of those was agent-written with neither
    approval lineage nor operator trust, because at the time neither was
    asked for. The first compile after an upgrade therefore emptied a
    project's whole Code of Law with no message, no diff explanation and no
    way back. A version flag in a config file would fix the symptom and
    leave no trace; this writes ONE `decision` through the archive's normal
    append, so the grandfathering is hash-chained, dated, attributable and
    readable by `godmode history` like any other fact.

    WHAT IT GRANDFATHERS. Every guarded, living lesson recorded before
    `GATE_SHIPPED_DATE` - "the state the project was already operating
    under" - and nothing else. The cutoff written down is the newest of
    those lessons' own sequence, so the rule every reader applies afterwards
    is a plain `sequence <= cutoff` with no clock in it: the DATE decides
    once, here, and the SEQUENCE carries that decision forever. A lesson
    recorded after the gate shipped is outside the cutoff and is held to the
    gate as designed, even when it is a fresh record on a subject the
    migration grandfathered.

    WHY NOT THE ARCHIVE HEAD. Because "everything already in the archive"
    is satisfied on a brand-new project by an agent appending its own guard
    and then compiling, which is the self-legislation the gate exists to
    refuse (`tests/test_law.py::test_an_agent_written_guard_is_not_law_
    without_an_approval`). The head is recorded alongside the cutoff so the
    record still says where the archive stood, but it grants nothing.

    IDEMPOTENT. One migration record per archive, keyed on kind+subject: a
    second run finds it and writes nothing, so a compile in a loop, a
    SessionStart hook and a `law compile` by hand all agree.
    """
    live, cutoff, head = _live_guarded_lesson_records(archive)
    if cutoff:
        return None
    pre_gate = [record for record in live
                if not lesson_carries_authority(record)
                and _recorded_before_the_gate(record)]
    if not pre_gate:
        return None
    pre_gate.sort(key=lambda record: int(record.get("sequence", 0)))
    subjects = [str(record.get("subject", ""))[:120] for record in pre_gate]
    citations = [f"seq:{int(record.get('sequence', 0))}" for record in pre_gate]
    # The cutoff is the NEWEST grandfathered lesson's own sequence, not the
    # archive head: sequences are monotonic in time, so everything at or
    # below it was recorded no later than that lesson - already pre-gate -
    # while the head would take in anything an agent appended between the
    # upgrade and this first compile. The head is recorded alongside it so
    # the record still says where the archive stood at migration time.
    cutoff_seq = int(pre_gate[-1].get("sequence", 0))
    value = (
        f"{len(pre_gate)} guarded lesson(s) recorded before {GATE_SHIPPED_DATE} "
        f"(at or below seq:{cutoff_seq}, archive head seq:{head}) predate the "
        "law authority gate and keep their standing; every lesson recorded "
        "after that sequence needs a second actor's approval, as designed."
    )
    record = archive.append(
        LAW_MIGRATION_KIND,
        LAW_MIGRATION_SUBJECT,
        {
            # NS-11c's semantic-decision shape, supplied in full: this is a
            # fact about the project, and it should read like one.
            "subject": LAW_MIGRATION_SUBJECT,
            "value": value,
            "evidence": citations,
            "cutoff_seq": cutoff_seq,
            "head_seq": int(head),
            "gate_shipped": GATE_SHIPPED_DATE,
            "grandfathered": len(pre_gate),
            "subjects": subjects,
        },
        evidence=citations,
    )
    return {
        "sequence": int(record.get("sequence", 0)),
        "cutoff_seq": cutoff_seq,
        "head_seq": int(head),
        "grandfathered": len(pre_gate),
        "subjects": subjects,
    }


def compile_laws(archive: Any, project: Path | str, *, cap: int = LAW_CAP) -> dict[str, Any]:
    """Fold guarded lessons into the law file and its wrapper skill.

    The compile path owns the one-time grandfather migration (above): it is
    the first thing that reads the gate on an upgraded archive, so it is
    where the line gets drawn, once, before anything is rendered.
    """
    root = Path(project)
    migration = grandfather_pre_gate_lessons(archive)
    lessons = _guarded_lessons(archive)
    skipped = sum(
        1 for record in archive.read_events()
        if record.get("kind") == "lesson"
        and not str((record.get("data") or {}).get("generalized_guard") or "").strip()
    )
    kept, dropped = lessons[:cap], max(0, len(lessons) - cap)
    (root / LAW_FILENAME).write_text(_render(kept, dropped, cap), encoding="utf-8")
    skill_dir = root / "skills" / SKILL_DIRNAME
    skill_dir.mkdir(parents=True, exist_ok=True)
    (skill_dir / "SKILL.md").write_text(_SKILL_BODY, encoding="utf-8")
    return {
        "laws": len(kept),
        "dropped_over_cap": dropped,
        "skipped_without_guard": skipped,
        "grandfathered": sum(1 for lesson in kept if lesson.get("grandfathered")),
        "pending_amendments": sum(1 for lesson in kept if lesson.get("pending_amendment")),
        "migration": migration,
        "cap": cap,
        "path": LAW_FILENAME,
        "skill": f"skills/{SKILL_DIRNAME}/SKILL.md",
    }
