#!/usr/bin/env python3
"""Generates `docs/COMMAND-REFERENCE.md` from the CLI's own parser, so the
public command reference cannot drift from what `--help` actually says.

Every row's Purpose is the exact help text `_build_parser()` declares for
that verb - never retyped by hand. `tests/test_command_reference_drift.py`
guards this two ways: the committed file must still be exactly what this
script would write today, and every verb the live parser accepts must have
a row (so a new verb added without regenerating fails a test immediately,
not a downstream `selftest` run days later).

Most rows verify with `--help` (always resolves, always accurate, and
never claims more than that the command exists). A small, curated set of
verbs that already carry a dedicated `tests/test_verb_<verb>.py` module or
an authored README section introducing them specifically - both added
while closing NS-7's orphan-verb list - point the Verify column at that
stronger, already-existing check instead; see `_VERIFY_OVERRIDES` below.
Every other verb keeps `--help`.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
SCRIPTS_DIR = REPO_ROOT / "scripts"
if str(SCRIPTS_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPTS_DIR))

from godmode_runtime.godmode_console import _build_parser  # noqa: E402

DOC_PATH = REPO_ROOT / "docs" / "COMMAND-REFERENCE.md"

_VERIFY_OVERRIDES: dict[str, str] = {
    "assurance": "`tests/test_verb_assurance.py`",
    "ceilings": "`tests/test_verb_ceilings.py`",
    "rewind": "`tests/test_verb_rewind.py`",
    "sop": "`tests/test_verb_sop.py`",
    "explain-context": 'see README "Continuity across sessions"',
    "reflect": 'see README "Verdicts"',
    "locale": 'see README "Quality, freshness, and the watchdog"',
    "absorb": 'see README "Minimality and upstream drift"',
}


def verbs_and_help() -> list[tuple[str, str]]:
    """Every top-level verb and its own help text, read from the live parser."""
    parser = _build_parser()
    rows: list[tuple[str, str]] = []
    for action in parser._actions:  # noqa: SLF001 - argparse exposes no public choices API
        if getattr(action, "choices", None):
            for pseudo in getattr(action, "_choices_actions", []):  # noqa: SLF001
                rows.append((pseudo.dest, pseudo.help or ""))
    rows.sort(key=lambda row: row[0])
    return rows


def verify_for(verb: str) -> str:
    return _VERIFY_OVERRIDES.get(verb, f"`godmode {verb} --help`")


def render() -> str:
    """The full markdown document, byte-for-byte what should be committed."""
    lines = [
        "# Command reference",
        "",
        "Every top-level verb, its purpose, and a command that verifies it is "
        "real. Generated by `scripts/dev/build_command_reference.py` from the "
        "CLI's own parser (`scripts/godmode_runtime/godmode_console.py`'s "
        "`_build_parser`) - regenerate rather than hand-edit when a verb's "
        "help text changes; `tests/test_command_reference_drift.py` fails if "
        "this file and the live parser ever disagree. Most rows verify with "
        "`--help` (always resolves, always accurate); a verb that already "
        "carries a dedicated test module or an authored README section "
        "points the Verify column at that instead. See "
        "`skills/godmode/references/godmode-command-surface.md` for the "
        "same surface from the routing skill's side.",
        "",
        "| Command | Purpose | Verify |",
        "| --- | --- | --- |",
    ]
    for verb, help_text in verbs_and_help():
        purpose = help_text.replace("|", "\\|")
        lines.append(f"| `{verb}` | {purpose} | {verify_for(verb)} |")
    lines.append("")
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--stdout", action="store_true",
                         help="print the table instead of writing docs/COMMAND-REFERENCE.md")
    args = parser.parse_args(argv)

    text = render()
    if args.stdout:
        sys.stdout.write(text)
    else:
        DOC_PATH.write_text(text, encoding="utf-8", newline="\n")
        print(f"wrote {DOC_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
